services:
  avr-asterisk:
    image: intelnexoec/avr-asterisk:latest
    container_name: avr-asterisk
    restart: always
    ports:
      - 5038:5038
      - 5060:5060
      - 8088:8088
      - 8089:8089
      - 10000-10050:10000-10050/udp
    volumes:
      - ./asterisk/conf:/etc/asterisk:rw
      - ../avr-app-main/data/recordings:/var/spool/asterisk/monitor:rw
    networks:
      - avr